### PR TITLE
Backport modern ignore list

### PR DESCRIPTION
**Pull request by cyberdelia**
Backport modern ignore list from upstream.

### CODE REVIEW

**Review by keiko713 — APPROVED** [review]
https://github.com/wal-e/wal-e/blob/master/wal_e/tar_partition.py#L467-L477

lgtm

**Comment by genslein** [comment]
@cyberdelia we shouldn't be using this anymore according @gregburek that we were using the public wal-e before he went on break. Can we confirm this is still used?

**Comment by cyberdelia** [comment]
@genslein We are definitely still using our fork.

**Comment by genslein** [comment]
😢 yay python 3 👍

**Pull request merged**
